name: Publish

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            TEST_TASK: macosX64Test
          - os: windows-latest
            TEST_TASK: mingwX64Test
          - os: ubuntu-latest
            TEST_TASK: check
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: ${{matrix.TEST_TASK}} --stacktrace
      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip
  deploy:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
        include:
          - os: macos-latest
            DEPLOY_TASK: :clikt:publish
          - os: windows-latest
            DEPLOY_TASK: :clikt:publishMingwX64PublicationToMavenRepository
    needs: test
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: ${{matrix.DEPLOY_TASK}} --stacktrace -PinferVersion=true

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx5g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
